### Dropwizard skeleton configuration file
##
## Do not commit changes that contain credentials or sensitive data!

server:
  rootPath: /api/v1/*
  applicationConnectors:
    - type: https
      port: 8080
      keyStorePath: /path/to/development.keystore
      keyStorePassword: password
      certAlias: development
      trustStorePath: /path/to/development.truststore
      supportedProtocols:
        - TLSv1.1
        - TLSv1.2
  adminConnectors:
    - type: https
      port: 8081
      keyStorePath: /path/to/development.keystore
      keyStorePassword: password
      certAlias: development
      trustStorePath: /path/to/development.truststore
      supportedProtocols:
        - TLSv1.1
        - TLSv1.2

logging:
  loggers:
      org.hibernate.SQL: ALL
  appenders:
    - type: console
      threshold: ALL
      target: stdout
    - type: file
      currentLogFilename: logs/students-api.log
      archivedLogFilenamePattern: logs/students-api-%d.log.gz
      archivedFileCount: 5
      threshold: ALL
      timeZone: PST

authentication:
  - username: username
    password: password

api:
  endpointUri: https://api.oregonstate.edu/v1

database:
  driverClass: oracle.jdbc.OracleDriver
  url: jdbc:oracle:thin:@//oracledb.example.com
  user: user
  password: pass
  properties:
      hibernate.dialect: org.hibernate.dialect.Oracle10gDialect
  validationQuery: "SELECT 1 FROM dual"
  initialSize: 2
  minSize: 1
  maxSize: 5

httpDataSource:
  endpoint: https://api.example.com/StudentApi
  username: username
  password: password

httpClient:
  # The socket timeout value. If a read or write to the underlying
  # TCP/IP connection hasn't succeeded after this duration, a
  # timeout exception is thrown.
  timeout: 60000ms

  # The connection timeout value. If a TCP/IP connection cannot be
  # established in this time, a timeout exception is thrown.
  connectionTimeout: 60000ms

  timeToLive: 1h
  cookiesEnabled: false
  maxConnections: 1024
  maxConnectionsPerRoute: 1024
  keepAlive: 0ms
  retries: 0
  userAgent: students-api
