swagger: '2.0'
info:
  title: Students API
  description: Get information about students at OSU.
  version: "1.0.0"
  license:
    name: GNU Affero General Public License Version 3
    url: http://www.gnu.org/licenses/agpl-3.0.en.html
externalDocs:
  description: GitHub Repository
  url: https://github.com/osu-mist/students-api
schemes:
  - https
basePath: /v1/students
produces:
  - application/json
paths:
  /{osuID}:
    get:
      description: Get general student information
      parameters:
        - $ref: '#/parameters/osuID'
      responses:
        200:
          description: Successful response
          schema:
            $ref: '#/definitions/StudentResultObject'
        404:
          description: Student not found
          schema:
            $ref: '#/definitions/Error'
  /{osuID}/academicstatus:
    get:
      description: Get a student's academic status for a given term.
      parameters:
        - in: query
          name: term
          required: true
          description: "Term code. Example: 201802"
          type: string
        - $ref: '#/parameters/osuID'
        - $ref: '#/parameters/pretty'
      responses:
        200:
          description: Successful response
          schema:
            $ref: '#/definitions/StatusResultObject'
        400:
          description: Bad request
          schema:
            $ref: '#/definitions/Error'
        404:
          description: Student not found
          schema:
            $ref: '#/definitions/Error'
  /{osuID}/workstudy:
    get:
      description: Get a student's available work study funding for a given date.
      parameters:
        - $ref: '#/parameters/osuID'
        - $ref: '#/parameters/pretty'
      responses:
        200:
          description: Successful response
          schema:
            $ref: '#/definitions/WorkStudyResultObject'
        404:
          description: Student not found
          schema:
            $ref: '#/definitions/Error'

parameters:
  osuID:
    name: osuID
    in: path
    required: true
    description: OSU ID of person
    type: string
  pretty:
    name: pretty
    in: query
    type: boolean
    required: false
    description: If true, JSON response will be pretty-printed

definitions:
  StudentResultObject:
    properties:
      data:
        properties:
          id:
            type: string
            description: 9 digit OSU ID
            example: 931234567
          type:
            type: string
            example: students
          attributes:
            properties:
              degrees:
                type: array
                items:
                  properties:
                    degree:
                      type: string
                      example: BS
                    degreeDescription:
                      type: string
                      example: Bachelor of Science
                    degreeCategoryDescription:
                      type: string
                      example: Baccalaureate Degree
                    status:
                      type: string
                      description: Degree status
                      example: Baccalaureate awarded
                    majorDescription:
                      type: string
                      example: Business Administration
                    levelDescription:
                      type: string
                      example: Undergraduate
                    collegeDescription:
                      type: string
                      example: College of Business
                    graduated:
                      type: boolean
                      example: false
                    campusDescription:
                      type: string
                    gpa:
                      type: number
                      format: float
                      description: Overall GPA
                      example: 3.5
          links:
            $ref: "#/definitions/SelfLink"
  StatusResultObject:
    properties:
      data:
        properties:
          id:
            type: string
            description: Term code
            example: "201801"
          type:
            type: string
            example: academicstatus
          links:
            $ref: "#/definitions/SelfLink"
          attributes:
            properties:
              osuHours:
                type: integer
                example: 15
                description: Number of credit hours currently enrolled at OSU
              dualEnrollmentHours:
                type: integer
                example: 7
                description: |
                  Number of credit hours currently enrolled at an institution 
                  outside of OSU as part of a dual enrollment program
              academicStanding:
                type: string
                example: Good Standing
                description: Academic standing
                enum:
                  - "Good Standing"
                  - "Academic Dismissal - Graduate"
                  - "Continued Deferred Suspension"
                  - "Honor Roll"
                  - "Academic Probation"
                  - "Special Deferred Suspension"
                  - "Academic Suspension"
                  - "Deferred Suspension"
                  - "Academic Warning"
                  - "Reinstatement After Suspension"
              registrationBlocked:
                type: boolean
                example: false
                description: If true, the current academic standing prevents registration
              academicProbation:
                type: boolean
                example: false
                description: If true, the current academic standing indicated academic probation
  WorkStudyResultObject:
    properties:
      data:
        properties:
          id:
            type: string
            example: null
          type:
            type: string
            example: workstudy
          links:
            $ref: "#/definitions/SelfLink"
          attributes:
            properties:
              awards:
                type: array
                items:
                  properties:
                    effectiveStartDate:
                      type: string
                      format: date
                      description: Date the award is effective.
                    effectiveEndDate:
                      type: string
                      format: date
                      description: Date the award is no longer effective.
                    offerAmount:
                      type: number
                      format: float
                      description: Dollar amount offered for the award.
                    offerExpirationDate:
                      type: string
                      format: date
                      description: Expiration date of offer.
                    acceptedAmount:
                      type: number
                      format: float
                      description: Dollar amount accepted by awardee.
                    acceptedDate:
                      type: string
                      format: date
                      description: Date the offer was accepted by the awardee.
                    paidAmount:
                      type: number
                      format: float
                      description: Dollar amount of the acceptedAmount that has been paid to the awardee.
                    awardStatus:
                      type: string
                      example: Accepted
                      description: Status of award.
                      enum:
                        - "Declined"
                        - "Offered"
                        - "System Accepted"
                        - "System Cancelled"
                        - "Estimated Auto Accept"
                        - "Estimated"
                        - "Recommended"
                        - "Accepted"
                        - "Certified"
                        - "System Offered"
                        - "Canceled"
  SelfLink:
    properties:
      self:
        type: string
        format: url
        description: Self link of resource
  Error:
    properties:
      status:
        type: integer
        description: HTTP status code.
      developerMessage:
        type: string
        description: An error string aimed at developers.
      userMesage:
        type: string
        description: An error string aimed at end users.
      code:
        type: integer
        description: Error code.
      details:
        type: string
        description: A link to further information about the error.
